const movieTypes = {
  SET_MOVIE_LIST: `SET_MOVIE_LIST`,
  UPDATE_NOMINATE_LIST: `UPDATE_NOMINATE_LIST`,
  REMOVE_FROM_NOMINATE_LIST: `REMOVE_FROM_NOMINATE_LIST`,
  ADD_NEW_MOVIE: `ADD_NEW_MOVIE`,
  UPDATE_MOVIES_LIST: `UPDATE_MOVIES_LIST`
}

export default movieTypes;
