const userTypes = {
  SET_CURRENT_USER: `SET_CURRENT_USER`,
  SET_LOGGED_IN_STATUS: `SET_LOGGED_IN_STATUS`,
  SET_ERRORS_ON_LOGGIN: `SET_ERRORS_ON_LOGGIN`,
  SET_ERRORS_ON_SIGN_UP: `SET_ERRORS_ON_SIGN_UP`
}

export default userTypes;
